/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Modifiers {
  Alt = 1,
  Control = 2,
  Shift = 4,
  Win = 8
}
export declare function registerHotkey(modifier: Modifiers, vk: number, callback: (...args: any[]) => any): void
export declare function openWebview(title: string, width: number, height: number): WebviewHandle
export declare class WebviewHandle {
  exit(): void
  setTitle(title: string): void
  setVisible(visible: boolean): void
}
