/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Modifiers {
  Alt = 1,
  Control = 2,
  Shift = 3,
  Win = 4
}
export declare function registerHotkey(modifier: Modifiers, vk: number, callback: (...args: any[]) => any): void
