name: Build iohook for Windows (Node.js v22)

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js v22
    - name: Set up Node.js v22
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build iohook for Windows (and any other necessary build steps)
    - name: Build iohook
      run: npm run build  # You might need to adjust the build command based on iohook's setup

    # Step 5: Create a Release
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./build/Release/iohook.node  # Adjust the path if needed, make sure this is the built file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
